basePath: /api
definitions:
  model.Subscription:
    properties:
      end_date:
        type: string
      id:
        type: string
      price:
        type: integer
      service_name:
        type: string
      start_date:
        type: string
      user_id:
        type: string
    type: object
host: localhost:8080
info:
  contact: {}
  description: Это API для управления подписками
  title: Subscription Aggregator API
  version: "1.0"
paths:
  /subscriptions/{id}:
    delete:
      description: Удаляет подписку по ID
      parameters:
      - description: ID подписки
        in: path
        name: id
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            additionalProperties:
              type: string
            type: object
        "500":
          description: Internal Server Error
          schema:
            additionalProperties:
              type: string
            type: object
      summary: Удаление подписки
      tags:
      - Подписки
    get:
      description: Возвращает подписку по её идентификатору
      parameters:
      - description: ID подписки
        in: path
        name: id
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/model.Subscription'
        "500":
          description: Internal Server Error
          schema:
            additionalProperties:
              type: string
            type: object
      summary: Получение подписки по ID
      tags:
      - Подписки
    put:
      consumes:
      - application/json
      description: Обновляет существующую подписку по ID
      parameters:
      - description: ID подписки
        in: path
        name: id
        required: true
        type: string
      - description: Новый ID пользователя
        in: query
        name: user_id
        type: string
      - description: Новое название сервиса
        in: query
        name: service_name
        type: string
      - description: Новая стоимость подписки
        in: query
        name: price
        type: integer
      - description: Новая начальная дата (yyyy-mm-dd)
        in: query
        name: from
        type: string
      - description: Новая конечная дата (yyyy-mm-dd)
        in: query
        name: to
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            additionalProperties:
              type: string
            type: object
        "500":
          description: Internal Server Error
          schema:
            additionalProperties:
              type: string
            type: object
      summary: Обновление подписки
      tags:
      - Подписки
  /subscriptions/{user_id}:
    post:
      description: Создает новую подписку
      parameters:
      - description: ID пользователя
        in: path
        name: user_id
        required: true
        type: string
      - description: Название сервиса
        in: query
        name: service_name
        required: true
        type: string
      - description: Стоимость подписки
        in: query
        name: price
        required: true
        type: integer
      - description: Начальная дата (yyyy-mm-dd)
        in: query
        name: from
        required: true
        type: string
      - description: Конечная дата (yyyy-mm-dd)
        in: query
        name: to
        type: string
      produces:
      - application/json
      responses:
        "201":
          description: Created
          schema:
            $ref: '#/definitions/model.Subscription'
        "500":
          description: Internal Server Error
          schema:
            additionalProperties:
              type: string
            type: object
      summary: Создание подписки
      tags:
      - Подписки
  /subscriptions/{user_id}/list/:
    post:
      consumes:
      - application/json
      description: Получение списка подписок по фильтру НИКНЕЙМ ПОЛЬЗОВАТЕЛЯ
      parameters:
      - description: user_id
        in: path
        name: user_id
        required: true
        type: string
      - description: page
        in: query
        name: page
        required: true
        type: integer
      - description: page_size
        in: query
        name: page_size
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            items:
              $ref: '#/definitions/model.Subscription'
            type: array
        "500":
          description: Internal Server Error
          schema:
            additionalProperties:
              type: string
            type: object
      summary: Список подписок
      tags:
      - Подписки
  /subscriptions/user/{user_id}/total:
    get:
      description: Подсчет общей суммы расходов по подпискам пользователя за период
      parameters:
      - description: ID пользователя
        in: path
        name: user_id
        required: true
        type: string
      - description: Название сервиса
        in: query
        name: service_name
        type: string
      - description: Начальная дата (yyyy-mm-dd)
        in: query
        name: from
        type: string
      - description: Конечная дата (yyyy-mm-dd)
        in: query
        name: to
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            additionalProperties: true
            type: object
        "400":
          description: Bad Request
          schema:
            additionalProperties:
              type: string
            type: object
        "500":
          description: Internal Server Error
          schema:
            additionalProperties:
              type: string
            type: object
      summary: Сумма расходов
      tags:
      - Подписки
schemes:
- http
swagger: "2.0"
